# Bepaling van soortelijke warmte van water


# Introductie

Water heeft een enorme buffercapaciteit: je moet veel energie toevoegen om de temperatuur van water een graad te verwarmen. In dit practicum gaan we de soortelijke warmte van water bepalen door een bekende hoeveelheid water te verwarmen met een bekende hoeveelheid energie, en de temperatuurstijging te meten.

# Theorie

Geef hier de natuurkundige achtergrond van het onderwerp. 

Om de soortelijke warmte te bepalen, kan de algemene formule voor warmte gebruikt worden;

$$
    Q = c \cdot m \cdot \Delta T
$$

In dit experiment worden de temperaturen, tijden en de massa van het water bepaald. Ook zijn een voltage en een stroom bekend waarmee Q bepaald kan worden;

$$
    E = Q = U \cdot I \cdot t
$$

Door vervolgens de formule voor warmte te herschikken kan de soortelijke warmte met alle bekende variabelen berekend worden.

$$
    c = \frac{Q}{m \Delta T}
$$ 

# Methode en materialen

## Ontwerp
Een waterbad met bekende massa aan water wordt verwarmd met een elektrisch verwarmingselement dat een bekende hoeveelheid energie levert.
De temperatuur van het water wordt gemeten met een temperatuursensor.
Door de temperatuurstijging als functie van de tijd te meten kan de soortelijke warmte van water worden berekend.


## Materialen
Hieronder staat de lijst van benodigde materialen bij deze proef:
- Maatbeker
- Weegschaal
- Water
- Elektrisch verwarmingselement ($10 \mathrm{\Omega}$, $10 \mathrm{W}$)
- Voedingsbron 
- Thermometer of temperatuursensor
- Stopwatch of timer

```{figure} figures/cwater_setup.jpg
:width: 70%

Een schematische weergave van de opstelling
```

## Procedure
```{exercise}
1. Beschrijf de procedure die nodig is om de soortelijke warmte van water te bepalen.
2. Geef jouw beschrijving van de procedure aan een ander team, zij verzamelen voor jou de data op basis van de gegevens.
3. Voer het experiment van een ander team uit op basis van hun beschrijving.
4. Analyseer de data die het andere groepje voor jou heeft verzameld.

- weeg een bepaalde massa van water af.
- meet de temp van het water.
- start timer.
- voeg energie toe aan het water tot het water met 1 graden is verhoogd.
- stop timer en noteer tijd.
- noteer het aantal benodigde energie.

```


## Veiligheid
We maken gebruik van een $10 \mathrm{\Omega}$, $10 \mathrm{W}$ weerstand.
Deze wordt snel heet.
De bronspanning mag dan ook alleen aan wanneer de weerstand in het water zit.
Raak de weerstand niet aan tijdens het experiment.
Omdat de weerstand in het water zit, kunnen we wel het elektrisch vermogen hoger zetten zonder dat de weerstand oververhit raakt.
Het maximaal vermogen mag $40 \mathrm{W}$ zijn.
Daarbij moet de roerder wel aanstaan om de warmte goed te verdelen.

## Data analyse
Geef kort de data-analysemethode weer.

In [1]:
#De gemeten gegevens kunnen direct worden ingevuld in de herschikte formule van de warmte

# Resultaten


In [ ]:
# Gegeven:
T_start = 30.2 # initial temperature in Celsius
T_final = 33.1 # final temperature in Celsius
dT = T_final - T_start # change in temperature in Celsius or Kelvin
t = 80.24 # time in seconds

V_water = 0.400 # volume of water in liters
M_water = V_water * 0.997 # mass of water in kilograms (density of water ~0.997 kg/L)

# Berekeningen:
U_1 = 11.9 # voltage in Volts
I_1 = 1.24 # current in Amperes
Q = U_1 * I_1 * t # energy supplied in Joules
R = U_1 / I_1 # resistance in Ohms
P = U_1 * I_1 # power in Watts

# Resultaten weergeven
print(f"De weerstand van het verwarmingselement is ongeveer {R:.2f} Ohm.")
print(f"Het vermogen van het verwarmingselement is ongeveer {P:.2f} Watt.")

# Berekenen van de specifieke warmtecapaciteit
c = Q / (M_water * dT) # specific heat capacity in J/(kg°C)
print(f"De specifieke warmtecapaciteit van water volgens dit experiment is ongeveer {c:.2f} J/(kg°C). De bekende warmtecapaciteit van water is 4186 J/(kg°C).")

De weerstand van het verwarmingselement is ongeveer 9.60 Ohm.
Het vermogen van het verwarmingselement is ongeveer 14.76 Watt.
De specifieke warmtecapaciteit van water volgens dit experiment is ongeveer 1023.78 J/(kg·°C). De bekende warmtecapaciteit van water is 4186 J/(kg·°C).


# Discussie en conclusie
De gevonden warmtecapaciteit van water is in dit experiment ongeveer vier keer lager dan de bekende waarde. Verschillende factoren hebben een rol kunnen spelen in deze significante afwijking. De meest voor de hand liggende verklaring is dat het water tijdens het opwarmen niet voldoende geroerd is; hier waren namelijk wat problemen mee tijdens het uitvoeren van het experiment. De temperaturen zouden verkeerd gemeten kunnen zijn door het apparaat en er zou vanaf een verkeerd moment begonnen zijn met het meten van de tijd. 
Een menselijke fout is bijna uit te sluiten, omdat het grootste deel van het experiment berustte op digitale meetapparatuur. Ook is het uit te sluiten dat het verwarmingselement op een te hoge stand stond; deze kan namelijk tussen 10W en 40W vermogen gezet worden en stond in dit experiment op ongeveer 15W. Een (te) hoge stand zou zorgen voor een lagere warmtecapaciteit, wat uit te sluiten is omdat het verwarmingselement op een lage stand stond.

In conclusie is dit experiment niet geslaagd; met ongeveer 1024 J/kg°C komt dit experiment ongeveer vier keer lager uit dan de werkelijke waarde van de warmtecapaciteit van water; 4186 J/kg°C. Dit zou kunnen komen door problemen met het meetapparatuur tijdens het experiment, of fouten in het gebruik van dit apparatuur.